export const TRADE_CATEGORIES = [
  'Building & Construction',
  'Plumbing',
  'Electrical',
  'Painting & Decorating',
  'Roofing',
  'Carpentry',
  'Plastering & Gib Stopping',
  'Tiling',
  'Flooring',
  'Landscaping & Gardening',
  'Fencing',
  'Concreting',
  'Decking',
  'Bricklaying & Blocklaying',
  'Glazing & Windows',
  'Kitchen & Bathroom',
  'Heating, Cooling & HVAC',
  'Handyman / General',
  'Cleaning',
  'Other',
];
